---

- name: install nginx
  hosts: db
  gather_facts: yes
  become: true

  tasks:
    - name: update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: upgrade all packages
      ansible.builtin.apt:
        upgrade: dist

    - name: add GPG key
      ansible.builtin.apt_key:
        url: https://www.mongodb.org/static/pgp/server-7.0.asc
        state: present

    - name: Add the MongoDB repository
      ansible.builtin.apt_repository:
        repo: "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/7.0 multiverse"
        state: present
        update_cache: yes

    - name: Install MongoDB 7.0
      ansible.builtin.apt:
        name: mongodb-org=7.0.6
        state: present

##########################################
# EXPLANATION OF PLAYBOOK
# ---                                         -> Marks the start of the YAML document.
#
# - name: install nginx                       -> Names the play “install nginx” (descriptive title shown in logs/output).
# hosts: db                                   -> Specifies that the play targets the [db] group of hosts defined in the inventory.
#
# gather_facts: yes                           -> Instructs Ansible to collect detailed information (facts) about the target host 
#                                                before running any tasks (e.g. OS version, release name, architecture).
#
# become: true                                -> Runs all tasks with elevated (sudo) privileges, which are required for system changes.
#
# tasks:                                      -> Begins the list of actions that Ansible will perform on the target hosts.
#
#   - name: update apt cache                  -> Refreshes the local package index from the repositories (equivalent to "apt update").
#     ansible.builtin.apt:                    -> Uses the built-in "apt" module for Debian/Ubuntu systems.
#       update_cache: yes                     -> Ensures the package cache is updated to get the latest package listings.
#
#   - name: upgrade all packages              -> Updates all installed packages to the latest available versions.
#     ansible.builtin.apt:                    -> Again uses the "apt" module.
#       upgrade: dist                         -> Performs a "distribution upgrade" (similar to "apt dist-upgrade") 
#                                                to intelligently handle dependencies and kernel upgrades.
#
#   - name: add GPG key                       -> Adds MongoDB’s official GPG key to verify the authenticity of packages.
#     ansible.builtin.apt_key:                -> Uses the "apt_key" module to manage trusted repository keys.
#       url: https://www.mongodb.org/static/pgp/server-7.0.asc
#                                              -> The URL where MongoDB’s GPG key can be downloaded from.
#       state: present                        -> Ensures the key exists on the system (adds it if missing, does nothing if already present).
#
#   - name: Add the MongoDB repository        -> Adds MongoDB’s official package repository to the system.
#     ansible.builtin.apt_repository:         -> Uses the "apt_repository" module to manage APT repo files.
#       repo: "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/7.0 multiverse"
#                                              -> Defines the repository source line (using a Jinja2 variable to match the OS release name).
#       state: present                        -> Ensures the repository is added (idempotent behaviour).
#       update_cache: yes                     -> Refreshes the package index after adding the new repository.
#
#   - name: Install MongoDB 7.0               -> Installs MongoDB version 7.0.6.
#     ansible.builtin.apt:                    -> Uses the "apt" module again for package installation.
#       name: mongodb-org=7.0.6               -> Specifies the exact package name and version to install.
#       state: present                        -> Ensures MongoDB is installed; does nothing if the correct version is already present.
##########################################
